### ISSUE TITLE
How to download the module "ti_plot_helper"

### ISSUE THREAD

**Issue by jabrena** [jpedrodias/Python-school#1]
Hi,

I am reviewing your repo and I would like learn how to download that module.

Many thanks in advance

Juan Antonio

**Comment by jabrena** [comment]
Solved

**Comment by jpedrodias** [comment]
Hello, I just upload a tns file (ti_plotlib_example.tns) with that code.

PS: This is just to prove a concept. Texas, CASIO and others could work together to produce an identical interface between devices.
